config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#index'

  get '/dashboard' => 'dashboard#index', :as => 'dashboard'
  get '/login' => 'sessions#new', :as => 'login'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  resource :sessions
  resources :users
  resource :dashboard
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password

  validates :email, :uniqueness => true,
            :length => {:within => 5..50}
  #Ver como fazer validação por REGEX para email
  #:format => { :with => /A[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}z/ }

  validates :password, :confirmation => true,
            :length => {:within => 4..20},
            :presence => true,
            :if => :password_required?

  has_many :trips

  before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
  def encrypt_new_password
    return if password.blank?
    self.hashed_password = encrypt(password)
  end

  def password_required?
    hashed_password.blank? || password.present?
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Make current_user available in templates as a helper
  helper_method :current_user

  #Make logged_in? availabe in templates as a Helper
  helper_method :logged_in?

  protected
  #Returns the currently logged in user or nil if there isn't one
  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end

  #Filter method to enforce a login requirement
  #Apply as a before_filter on any controller you want to protect
  def authenticate
    logged_in? ? true : access_denied
  end

  #Predicate method to test for a logged in user
  def logged_in?
    current_user.is_a? User
  end

  def access_denied
    redirect_to login_path, :notice => 'Please log in to continue' and return false
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if current_user.is_a? User
      render :action => 'show'
    end
  end

  def show

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path, :notice => 'Logged in successfully'
    else
      redirect_to root_path, :alert => 'Invalid login/password combination'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, :notice => 'You successfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def submit_or_cancel(form, name='Cancel')
    form.submit + " or " +
        link_to(name, 'javascript:history.go(-1);', :class => 'cancel')
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webpage_helper.rb
module WebpageHelper
end

app/views/dashboard/_login_form.html.erb
<h1>Login</h1>

<%= form_tag sessions_path do %>
    <div class='field'>
      <%= label_tag :email %> <br/>
      <%= text_field_tag :email %>
    </div>
    <div class='field'>
      <%= label_tag :password %> <br/>
      <%= password_field_tag :password %>
    </div>
    <div class='actions'>
      <%= submit_tag 'Login' %>
    </div>
<% end %>

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>First page</title>
</head>
<body>
<%= render 'login_form' %>
</body>
</html>

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripsurfWebServer</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">

</div>

<div id='main'>
  <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
  <%= content_tag :p, alert, :class => 'alert' if alert.present? %>
  <%= yield %>
</div>

<div id="footer">

</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id='errorExplanation'>
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user
            from being save; </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class='field'>
      <%= f.label :email %> <br/>
      <%= f.text_field :email %>
    </div>
    <div class='field'>
      <%= f.label :password %> <br/>
      <%= f.password_field :password %>
    </div>
    <div class='field'>
      <%= f.label :password_confirmation %> <br/>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class='actions'>
      <%= submit_or_cancel(f) %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><h3>User: <%= user.email %></h3></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h3>User: <%= @user.email %></h3>
<br/>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>